# This section is for textual information

In [ ]:
# to create an array we first need to import a NumPy module
import numpy as np

# Assignment Operators

Are used to assign value to a variable (store data)


*   Equals (Assign)
*   Plus Equals
*   Minus Equals
*   Multiply Equals

In [ ]:
# assign 10 to the variable x
x = 10
print(x)

# plus equals, y = y + 1
y = 1
y += 1
print(y)

# minus equals, z = z - 1
z = 1
z -= 1
print(z)

# multiply equals, m = m * 2
m = 2
m *= 2
print(m)

In [ ]:
# plus equals, y = y + 1
y = 1
y += 1
print(y)

2


In [ ]:
# minus equals, z = z - 1
z = 1
z -= 1
print(z)

0


In [ ]:
# multiply equals, m = m * 2
m = 2
m *= 2
print(m)

4


# Python Data Types

Variables are used to assign data types

**Numeric**

int, float, complex

In [ ]:
# an int (integer)
x = 10
print(type(x))


# a float type
y = 3.412
print(type(y))

# a complex type
z = 1j
print(type(z))

**String**

A string literal is surround by a single quotation mark, or a double quotation mark. However, a single quotation mark is consider a good readable style.

**Class Object**: str

In [ ]:
say_hi = 'hello, world'
print(type(say_hi))
print(say_hi)

**Sequences**

These are also called iterable objects i.e. an object that stores data that could be indexed and looped through.

**Class Object**:
list, tuple, range, arrays, dict (map)

In [ ]:
# list type
fruits = ['apples', 'oranges', 'bananas']
print(type(fruits))
print(fruits)

# tuples
fruitier = ('apples', 'oranges', 'bananas')
print(type(fruitier))
print(fruitier)

# range
x = range(6)
print(type(x))
print(x)

In [ ]:
# list explicit style

# list(())
fruits = list(('apples', 'oranges', 'bananas'))
print(fruits)
print(type(fruits))

**Tuples**
Properties:


*   Immutable which means: 
    (1) they can not be copied, (2) they have fixed length once created

*   Have structure (recall: lists have order)

In [ ]:
# tuples explicit style
fruitier = tuple(('apples', 'oranges', 'bananas'))
print(type(fruitier))
print(fruitier)


# this creates a copy of a list
new_fruits = list(fruits)
print('I am a new copy of fruits', new_fruits)
print('Am I fruits?', new_fruits is fruits)

# can not copy with tuples
new_fruitier = tuple(fruitier)
print('Am I still fruitier?', new_fruitier is fruitier)

# A note about lists


List items are enclosed in square brackets, like this [item1, item2, item3].

*   **Lists are ordered** i.e. the items in the list appear in a specific order, meaning if you add new items to a list, the new items will be placed at the end of the list.
*   **Lists are mutable**, which means we can add or remove items.
*   **List elements do not need to be unique**. Item duplication is possible, as each element has its own distinct indexed location in the list.
*   **Elements can be of different data types**, which means that you can combine strings, integers, and objects in the same list.

In [ ]:
# create a list with different data
my_mixed_list = ['abc', 7, True, 'male']
print(my_mixed_list)

# index location [0,1,2,3]
# get the last element
# my_mixed_list[3]
print(my_mixed_list[3])

# change male to female
my_mixed_list[3] = 'female'
print(my_mixed_list)

# append to list
my_mixed_list += ['007']
print(my_mixed_list)

# remove from list
my_mixed_list.remove('007')
print(my_mixed_list)

# remove from list with pop method
# needs to index to the element to be removed
# pop also returns the element removed
my_mixed_list.pop(3)
print('using pop', my_mixed_list)

# or use Python del operator - notice square brackets
del my_mixed_list[2]

# using a helper function to append to list
my_mixed_list.append('007')
print(my_mixed_list)

# Arrays

Like lists, an array is also a data structure that stores a collection of items. And like lists, arrays are:
* ordered
* mutable
* enclosed in square brackets
* store non-unique items

**NumPy**

NumPy is one of Python's most useful libraries: [NumPy](https://numpy.org/)

**Import keyword**

Is needed to make use of modules and libraries.

In [ ]:
# to create an array we first need to import a NumPy module
import numpy as np

# create an array containing numbers
# np.array()
my_array = np.array([1,3,5,7])
print(type(my_array))
print(my_array)

In [ ]:
# divide my array by 3 - this should divide every element in the array by 3
results = my_array / 3
print(results)

# try to divide a list by 3 - this should give us an error
my_list = list((1,3,5,7))
answer = my_list / 3
print(answer)

**Access and change elements stored in Arrays**

In [ ]:
# create an array named my_array
my_array = np.array([3,6,9,12])

In [ ]:
# get the first element in the array indexed 0
print(my_array[0])

3


In [ ]:
print(my_array)

[ 3  6  9 12]


In [ ]:
index_to_element = 2

In [ ]:
my_array[index_to_element] = 100

In [ ]:
print(my_array)

[ 18   6 100  12]


In [ ]:
# change the first element from 3 to 18
my_array[0] = 18

In [ ]:
print(my_array)

[18  6  9 12]


In [ ]:
# remove element from array
# require two arguments to numpy: (array_name, index)
index_to_element = 3

In [ ]:
my_array = np.delete(my_array, index_to_element)

In [ ]:
print(my_array)

[18  6  9]


In [ ]:
# add or append to array
my_array = np.append(my_array, [1,2,4])
print(my_array)

In [ ]:
# insert element at specific location
# needs: (array_name, index_of_location, element_to_insert)
index_of_location = 1
element_to_insert = 15
my_array = np.insert(my_array,index_of_location, element_to_insert)
print(my_array)

**Map or Dictionary Type**

**Class Object**: dict

In [ ]:
student = {
    'name': 'felipe',
    'age': 30,
    'unit': 'DATA4200'
}

In [ ]:
print(student)

{'name': 'felipe', 'age': 30, 'unit': 'DATA4200'}


In [ ]:
print(student['name'])

felipe


In [ ]:
print(student['age'])

30


In [ ]:
print(student['unit'])

DATA4200


**Dictionary with Many Elements**

In [ ]:
many_students = {1: {'name': 'felipe', 'age': 30, 'unit': 'DATA4200', 'gender': 'male'},
          2: {'name': 'hannah', 'age': '22', 'unit': 'DATA4200', 'gender': 'female'}}

In [ ]:
print(many_students)

{1: {'name': 'felipe', 'age': 30, 'unit': 'DATA4200', 'gender': 'male'}, 2: {'name': 'hannah', 'age': '22', 'unit': 'DATA4200', 'gender': 'female'}}


In [ ]:
print(many_students[1]['name'])

felipe


In [ ]:
print(many_students[2])

{'name': 'hannah', 'age': '22', 'unit': 'DATA4200', 'gender': 'female'}


In [ ]:
print(many_students[1])

{'name': 'felipe', 'age': 30, 'unit': 'DATA4200', 'gender': 'male'}


In [ ]:
many_many_students = {1: {'name': 'felipe', 'age': 30, 'unit': 'DATA4200', 'gender':''},
          2: {'name': 'hannah', 'age': '22', 'unit': 'DATA4200', 'gender':'', 'favourite_car':'tesla'}}

In [ ]:
print(many_many_students[2])

{'name': 'hannah', 'age': '22', 'unit': 'DATA4200', 'gender': '', 'favourite_car': 'tesla'}


In [ ]:
print(many_many_students[1]['favourite_car'])

In [ ]:
# create a storage for a person
person = {'Name': 'Mary', 'Age': 33}
print(type(person))
print(person)

# show person name
print(person['Name'])

# show person age
person['Age']

# can we get value using index? No because maps or dicts have named keys
# print(person[0])

# change person's age to 18
person['Age'] = 18
print(person)

In [ ]:
# dict explicit style
person = dict(Name = 'Mary', Age = 33)
print(type(person))
print(person)

**Boolean**

Booleans are True or False

When programming the case arises when you want to know if some expression is true or false

**Class Object**: bool

Bool() will always return True unless:
* The object is empty e.g. [], (), {}
* The object is False
* The object is 0
* The object is None

In [ ]:
# bool type
truthly = bool(1)
print(type(truthly))
print(truthly)

truthy = bool()
print(truthy)

In [ ]:
# when an expression is true or false
print(5 > 4)

In [ ]:
print(3 == 3)

In [ ]:
print(2 < 3)

In [ ]:
print(2 <= 3)

In [ ]:
print(2 >= 3)

# Python Arithmetics

Use to perform common math operations

*   Addition
*   Subtraction
*   Multiplication
*   Division
*   Modulus
*   Exponentiation



In [ ]:
# add two numbers
5 + 3

In [ ]:
# add two numbers
5 + 3

In [ ]:
# subtraction
10 - 5

In [ ]:
# multiplication
2 * 2

In [ ]:
# division
4 / 2

In [ ]:
# modulus
4 % 2

In [ ]:
# exponent or raise to the power
2 ** 4